spring:
  config:
    import: emv.yml
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: ${DB_STRATEGY}
  datasource:
    platform: ${DB_PLATFORM}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER}




